import type { Metadata } from "next";
import { Oswald } from 'next/font/google'
import "./globals.css";
import NavBar from "./components/NavBar";
import SessionContext from "./SessionContext";
const oswald = Oswald({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      <body className={`${oswald.className} bg-[url('/bg.jpg')]`}>
        <SessionContext>

          <NavBar />
          {children}
        </SessionContext>

      </body>
    </html>
  );
}
